spring.application.name=wagon-management
spring.datasource.url=jdbc:mysql://localhost:3306/wagon_management
spring.datasource.username=root
spring.datasource.password=Tejesh@1729810

spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true

# =====================================================
# JWT CONFIGURATION
# =====================================================

jwt.secret=RailFlowDevelopmentSecretKey2026ForJwtAuthentication123456789

# 1 hour
jwt.expiration=3600000

# ==========================================
# Email / SMTP Configuration
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sonyclark4561@gmail.com
spring.mail.password=uxvmuquxnvdbjujd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true