spring.application.name=wagon-management
spring.datasource.url=jdbc:mysql://localhost:3306/wagon_management
spring.datasource.username=root
spring.datasource.password=Tejesh@1729810

spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true